### ISSUE TITLE
[Feature] Headers

### ISSUE THREAD

**Issue by tsndr** [data-enabler/streamdeck-web-requests#1]
Hi, I've seen that it's still on your to-do list, but I'd like to get notified once you've implemented it so I'm creating this issue just to keep track of it :)

**Comment by data-enabler** [comment]
No problem!
I have a lot on my plate these days so I can't make any guarantees about when I'll get around to implementing this, since it's unlikely that I'll end up needing this feature for my own use cases.

Pull requests are welcome.

**Comment by zanechua** [comment]
Added it in #5. 

Would be great if you can merge it in.

Took about 45minutes to implement. Pretty straightforward.

Thanks for writing the initial plugin. Needed a plugin that worked cross-platform instead of API Ninja which only works on Windows.

**Comment by data-enabler** [comment]
Thanks! Currently on a trip, but I'll try to take a look once I'm back in a few days.
